package com.technology.jep.jepria.auto.model.user;

import java.util.List;

import com.technology.jep.jepria.auto.application.entrance.EntranceAuto;

public class User {
  
  private User(Integer operatorId, String operatorName, List<String> roles, String login, String password, boolean isFromDB) {
    this.operatorId = operatorId;
    this.operatorName = operatorName;
    this.roles = roles;
    this.login = login;
    this.password = password;
    this.isFromDB = isFromDB;
  }

  public static User fromDB(Integer operatorId, String operatorName, List<String> roles, String login, String password) {
    return new User(operatorId, operatorName, roles, login, password, true);
  }
  
  public static User fromLoginAndPassword(String login, String password) {
    return new User(null, null, null, login, password, false);
  }
  
  
  private Integer operatorId;
  private String operatorName;
  private List<String> roles;
  
  private String login;
  private String password;
  
  private boolean isFromDB;

  public String getLogin() {
    return login;
  }
  
  /**
   * @throws IllegalStateException если пользователь был создан методом {@link User#fromLoginAndPassword},
   * а не {@link User#fromDB}.
   */
  public Integer getOperatorId() throws IllegalStateException {
    checkFromDb();
    return operatorId;
  }
  /**
   * @return the password
   */
  public String getPassword() {
    return password;
  }

  /**
   * @throws IllegalStateException если пользователь был создан методом {@link User#fromLoginAndPassword},
   * а не {@link User#fromDB}.
   */
  public String getOperatorName() throws IllegalStateException {
    checkFromDb();
    return operatorName;
  }

  /**
   * @throws IllegalStateException если пользователь был создан методом {@link User#fromLoginAndPassword},
   * а не {@link User#fromDB}.
   */
  public List<String> getRoles() throws IllegalStateException {
    checkFromDb();
    return roles;
  }
  
  /**
   * Авторизация текущего пользователя. <br/>
   * Делает logout, если авторизован другой пользователь. 
   * @param cut Класс, реализующий авторизацию.
   */
  @Deprecated
  public void login(EntranceAuto cut){
    
    if(cut.isLoggedIn()) {
      cut.logout();
    }
    cut.login(this.getLogin(), this.getPassword());
  }

  /**
   * Generated by eclipse.
   */
  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("User [");
    if (operatorId != null) {
      builder.append("operatorId=");
      builder.append(operatorId);
      builder.append(", ");
    }
    if (operatorName != null) {
      builder.append("operatorName=");
      builder.append(operatorName);
      builder.append(", ");
    }
    if (roles != null) {
      builder.append("roles=");
      builder.append(roles);
      builder.append(", ");
    }
    if (login != null) {
      builder.append("login=");
      builder.append(login);
      builder.append(", ");
    }
    if (password != null) {
      builder.append("password=");
      builder.append(password);
    }
    builder.append("]");
    return builder.toString();
  }
  
  private void checkFromDb() throws IllegalStateException {
    if (!isFromDB) {
      throw new IllegalStateException("Cannot obtain User's property as it is not loaded from DB.");
    }
  }
}
