package com.technology.jep.jepria.auto.model;

import java.util.List;

import com.technology.jep.jepria.auto.entrance.EntranceAuto;

public class User {
  
  public User(Integer operatorId, String operatorName, List<String> roles, String login, String password) {
    super();
    this.operatorId = operatorId;
    this.operatorName = operatorName;
    this.roles = roles;
    this.login = login;
    this.password = password;
  }

  private Integer operatorId;
  private String operatorName;
  private List<String> roles;
  
  private String login;
  private String password;
  

  public String getLogin() {
    return login;
  }
  
  public Integer getOperatorId() {
    return operatorId;
  }
  /**
   * @return the password
   */
  public String getPassword() {
    return password;
  }

  public String getOperatorName() {
    return operatorName;
  }

  public List<String> getRoles() {
    return roles;
  }
  
  /**
   * Авторизация текущего пользователя. <br/>
   * Делает logout, если авторизован другой пользователь. 
   * @param cut Класс, реализующий авторизацию.
   */
  public void login(EntranceAuto cut){
    
    if(cut.isLoggedIn()) {
      cut.logout();
    }
    cut.login(this.getLogin(), this.getPassword());
  }

  /**
   * Generated by eclipse.
   */
  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("User [");
    if (operatorId != null) {
      builder.append("operatorId=");
      builder.append(operatorId);
      builder.append(", ");
    }
    if (operatorName != null) {
      builder.append("operatorName=");
      builder.append(operatorName);
      builder.append(", ");
    }
    if (roles != null) {
      builder.append("roles=");
      builder.append(roles);
      builder.append(", ");
    }
    if (login != null) {
      builder.append("login=");
      builder.append(login);
      builder.append(", ");
    }
    if (password != null) {
      builder.append("password=");
      builder.append(password);
    }
    builder.append("]");
    return builder.toString();
  }
}
