package org.jepria.server.data;

import java.util.Objects;

/**
 * Класс для представления опций в общем виде
 */
public class OptionDto<T> {
  
  public OptionDto() {}
  
  private String name;
  
  private T value;
  
  public String getName() {
    return name;
  }
  
  public void setName(String name) {
    this.name = name;
  }
  
  public T getValue() {
    return value;
  }
  
  public void setValue(T value) {
    this.value = value;
  }

  @Override
  public boolean equals(Object o) { // generated by IntelliJ Idea
    if (this == o) return true;
    if (!(o instanceof OptionDto)) return false;
    OptionDto<?> optionDto = (OptionDto<?>) o;
    return Objects.equals(getName(), optionDto.getName()) &&
            Objects.equals(getValue(), optionDto.getValue());
  }

  @Override
  public int hashCode() { // generated by IntelliJ Idea
    return Objects.hash(getName(), getValue());
  }
}
